# Build image
image: macos-monterey

install:
- curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal
- export PATH=$HOME/.cargo/bin:$PATH
- cargo fetch --locked

test_script:
# First, build all the tests
- cargo build --verbose --locked --offline --all-features --all-targets
# Then, add entitlement to all test binaries
- find target -perm +111 -type f -exec codesign -s - --entitlements endpoint-sec/Entitlement.plist --force {} \;
# Now we can run them
- cargo test

build: off
